### ISSUE TITLE
`v-pre` attribute doesn't help with displaying data with Jekyll/Liquid

### ISSUE THREAD

**Issue by greglgomez** [SteinHQ/Expedite#1]
Hi there,

I'm using Stein Expedite with a Jekyll site and Liquid also uses `{{ }}` however it doesn't seem like the `v-pre` attribute works to display data.

example here:
https://greglgomez.me/sandbox/fyp
https://github.com/greglgomez/www/blob/master/sandbox/fyp/index.html

Thanks for the great tool, loving it so far. :)

**Comment by shivensinha4** [comment]
Hey, Greg! v-pre is an attribute defined in Vue for indicating Vue to not treat the element as a template. For liquid, a quick search showed me that you need something like:

```
{% raw %}
  <div>{{role}}</div>
{% endraw %}
```

Let me know if it works!

**Comment by greglgomez** [comment]
yup, that works. Thanks for the tip, was stumped. :)
